# *** REPLCAE CERTAIN VARIABLE WITH YOUR APPLICATION VARIABLE ***

# Use an official OpenJDK runtime as a parent image
FROM openjdk:17

# Set the working directory to /app
WORKDIR /app

# Copy the JAR file into the container at /app
COPY target/your-application.jar .

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Define environment variable
ENV VARIABLE_NAME=value

# Run the application when the container launches
CMD ["java", "-jar", "your-application.jar"]

# Container Health Check (Optional): If you want to implement a health check for your application, 
# you can use the HEALTHCHECK instruction.
HEALTHCHECK --interval=30s --timeout=30s CMD curl -f http://localhost:8080/actuator/health || exit 1
